name: Build Open Telemetry Kitchen Sink

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build Snapshot
        run: mvn -B package --file otel-osgi/pom.xml
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: otel-osgi
          path: |
            otel-osgi/target/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set New Version
        run: mvn -f otel-osgi/pom.xml versions:set -DnewVersion=1.0.${{ github.run_number }}
      - name: Publish package
        run: mvn -f otel-osgi/pom.xml --batch-mode deploy -DuniqueVersion=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}